using Content.Client.SS220.Administration.Systems;
using Content.Client.UserInterface.Controls;
using Content.Client.Verbs.UI;
using Content.Shared.SS220.Administration.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Network;

namespace Content.Client.SS220.Administration.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class CustomObjectivesListControl : BoxContainer
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IUserInterfaceManager _uiManager = default!;

    private readonly CustomObjectivesSystem _customObjectives;
    private readonly Dictionary<NetUserId, CustomObjectivesPlayerInfo> _playerInfosBySession = new();
    private NetUserId? _selectedSessionId;

    private static readonly Color ListBackgroundColor = new(32, 32, 40);

    public event Action<CustomObjectivesPlayerInfo?>? OnSelectionChanged;

    public CustomObjectivesListControl()
    {
        IoCManager.InjectDependencies(this);
        _customObjectives = _entityManager.System<CustomObjectivesSystem>();
        RobustXamlLoader.Load(this);
        CustomObjectivesListContainer.ItemPressed += OnItemPressed;
        CustomObjectivesListContainer.GenerateItem += GenerateButton;
        BackgroundPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = ListBackgroundColor };
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _customObjectives.PlayerInfosChanged += UpdatePlayerList;
        UpdatePlayerList(_customObjectives.PlayerInfos);
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _customObjectives.PlayerInfosChanged -= UpdatePlayerList;
    }

    private void UpdatePlayerList(IReadOnlyList<CustomObjectivesPlayerInfo> playerInfos)
    {
        _playerInfosBySession.Clear();
        var listData = new List<ListData>(playerInfos.Count);
        foreach (var playerInfo in playerInfos)
        {
            _playerInfosBySession[playerInfo.SessionId] = playerInfo;
            listData.Add(new CustomObjectivesListData(playerInfo));
        }

        CustomObjectivesListContainer.PopulateList(listData);

        if (_selectedSessionId is not { } selectedSessionId)
            return;

        if (_playerInfosBySession.TryGetValue(selectedSessionId, out var selectedPlayerInfo))
        {
            OnSelectionChanged?.Invoke(selectedPlayerInfo);
            return;
        }

        _selectedSessionId = null;
        OnSelectionChanged?.Invoke(null);
    }

    private void OnItemPressed(BaseButton.ButtonEventArgs? args, ListData? data)
    {
        if (args is null || data is not CustomObjectivesListData { PlayerInfo: var playerInfo })
            return;

        if (args.Event.Function == EngineKeyFunctions.UIClick)
        {
            _selectedSessionId = playerInfo.SessionId;
            OnSelectionChanged?.Invoke(playerInfo);
            return;
        }

        if (args.Event.Function != EngineKeyFunctions.UseSecondary ||
            playerInfo.NetEntity is not { } netEntity ||
            !_entityManager.TryGetEntity(netEntity, out var entity) ||
            entity is not { } entityUid)
        {
            return;
        }

        _uiManager.GetUIController<VerbMenuUIController>().OpenVerbMenu(entityUid);
    }

    private void GenerateButton(ListData data, ListContainerButton button)
    {
        if (data is not CustomObjectivesListData { PlayerInfo: var playerInfo })
            return;

        button.AddChild(new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            Children =
            {
                new Label
                {
                    ClipText = true,
                    Text = Loc.GetString(
                        "admin-custom-objectives-entry",
                        ("character", playerInfo.CharacterName),
                        ("username", playerInfo.Username),
                        ("count", playerInfo.ObjectiveCount))
                }
            }
        });
        button.EnableAllKeybinds = true;
        button.AddStyleClass(ListContainer.StyleClassListContainerButton);
    }
}

public sealed record CustomObjectivesListData(CustomObjectivesPlayerInfo PlayerInfo) : ListData;
