using System.Linq;
using System.Numerics;
using Content.Shared.SS220.Arena.Lobby;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.SS220.Arena.Lobby;

[GenerateTypedNameReferences]
public sealed partial class ArenaLobbyWindow : DefaultWindow
{
    [Dependency] private readonly ILocalizationManager _loc = default!;

    private const string CategoryAll = "";

    public event Action<string>? OnCreateRequested;
    public event Action<uint>? OnJoinRequested;
    public event Action<uint>? OnObserveRequested;
    public event Action? OnRefreshRequested;

    private static readonly Vector2 ButtonMinSize = new(86, 0);
    private static readonly Thickness RowMargin = new(8, 6);
    private static readonly Thickness PlayersMargin = new(0, 0, 8, 0);
    private static readonly Thickness NoArenasMargin = new(0, 18, 0, 0);

    private static readonly Color ColorWaiting = Color.FromHex("#5dadd8");
    private static readonly Color ColorCountdown = Color.FromHex("#e0c46d");
    private static readonly Color ColorFighting = Color.FromHex("#e06b5d");
    private static readonly Color ColorFinished = Color.FromHex("#888888");
    private static readonly Color ColorCooldown = Color.FromHex("#e0c46d");
    private static readonly Color ColorDescription = Color.FromHex("#888888");

    private string _selectedCategory = CategoryAll;
    private ArenaLobbyEuiState? _lastState;
    private List<string> _knownCategories = new();

    public ArenaLobbyWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CooldownLabel.FontColorOverride = ColorCooldown;
        RefreshButton.OnPressed += _ => OnRefreshRequested?.Invoke();
    }

    public void Update(ArenaLobbyEuiState state)
    {
        _lastState = state;
        RebuildCategories(state);
        RebuildLists(state);
    }

    private void RebuildCategories(ArenaLobbyEuiState state)
    {
        var categories = state.Templates.Select(t => t.Category)
            .Concat(state.Arenas.Select(a => a.Category))
            .Where(c => !string.IsNullOrEmpty(c))
            .Distinct()
            .OrderBy(c => c)
            .ToList();

        if (_selectedCategory != CategoryAll && !categories.Contains(_selectedCategory))
            _selectedCategory = CategoryAll;

        if (_knownCategories.SequenceEqual(categories))
            return;
        _knownCategories = categories;

        CategoriesBar.RemoveAllChildren();
        CategoriesBar.AddChild(BuildCategoryButton(CategoryAll, "arena-lobby-category-all"));
        foreach (var cat in categories)
            CategoriesBar.AddChild(BuildCategoryButton(cat, $"arena-lobby-category-{cat}"));
    }

    private Button BuildCategoryButton(string category, string locKey)
    {
        var label = _loc.TryGetString(locKey, out var text) ? text : category;
        var button = new Button
        {
            Text = label,
            ToggleMode = true,
            Pressed = _selectedCategory == category,
        };
        button.OnPressed += _ =>
        {
            _selectedCategory = category;
            if (_lastState != null)
                RebuildLists(_lastState);
            foreach (var child in CategoriesBar.Children)
            {
                if (child is Button b)
                    b.Pressed = ReferenceEquals(b, button);
            }
        };
        return button;
    }

    private void RebuildLists(ArenaLobbyEuiState state)
    {
        CounterLabel.Text = Loc.GetString("arena-lobby-header",
            ("count", state.ActiveCount),
            ("max", state.MaxArenas));

        if (state.CreateCooldownRemaining > 0)
        {
            CooldownLabel.Visible = true;
            CooldownLabel.Text = Loc.GetString("arena-lobby-cooldown", ("cooldown", state.CreateCooldownRemaining));
        }
        else
        {
            CooldownLabel.Visible = false;
        }

        ArenasList.RemoveAllChildren();
        var filteredArenas = state.Arenas.Where(MatchesCategory).ToList();
        if (filteredArenas.Count == 0)
        {
            ArenasList.AddChild(new Label
            {
                Text = Loc.GetString("arena-lobby-no-arenas"),
                StyleClasses = { "LabelSubText" },
                HorizontalAlignment = HAlignment.Center,
                Margin = NoArenasMargin,
            });
        }
        else
        {
            foreach (var entry in filteredArenas)
                ArenasList.AddChild(BuildArenaRow(entry));
        }

        TemplatesList.RemoveAllChildren();
        var canCreate = state.ActiveCount < state.MaxArenas && !state.HasOwnArena && state.CreateCooldownRemaining <= 0;
        var sortedTemplates = state.Templates.Where(MatchesCategory).OrderBy(t => t.Name, StringComparer.Ordinal);
        foreach (var tmpl in sortedTemplates)
            TemplatesList.AddChild(BuildTemplateRow(tmpl, canCreate));
    }

    private static bool IsJoinablePhase(ArenaPhase phase) => phase == ArenaPhase.WaitingForPlayers;
    private static bool IsObservablePhase(ArenaPhase phase) => phase is ArenaPhase.WaitingForPlayers or ArenaPhase.Countdown or ArenaPhase.Fighting;

    private bool MatchesCategory(ArenaLobbyEntry entry) => _selectedCategory == CategoryAll || entry.Category == _selectedCategory;
    private bool MatchesCategory(ArenaLobbyTemplate tmpl) => _selectedCategory == CategoryAll || tmpl.Category == _selectedCategory;

    private PanelContainer BuildArenaRow(ArenaLobbyEntry entry)
    {
        var (statusKey, statusColor) = entry.Phase switch
        {
            ArenaPhase.WaitingForPlayers => ("arena-lobby-status-waiting", ColorWaiting),
            ArenaPhase.Countdown => ("arena-lobby-status-countdown", ColorCountdown),
            ArenaPhase.Fighting => ("arena-lobby-status-fighting", ColorFighting),
            _ => ("arena-lobby-status-finished", ColorFinished),
        };

        var name = new Label
        {
            Text = entry.Name,
            StyleClasses = { "LabelKeyText" },
        };

        var status = new Label
        {
            Text = $"[{Loc.GetString(statusKey)}]",
            FontColorOverride = statusColor,
        };

        var players = new Label
        {
            Text = $"{entry.Players}/{entry.MaxPlayers}",
            StyleClasses = { "LabelSubText" },
            HorizontalAlignment = HAlignment.Right,
            HorizontalExpand = true,
            Margin = PlayersMargin,
        };

        var join = new Button
        {
            Text = Loc.GetString("arena-lobby-join"),
            Disabled = !IsJoinablePhase(entry.Phase) || entry.Players >= entry.MaxPlayers,
            MinSize = ButtonMinSize,
        };
        var id = entry.ArenaId;
        join.OnPressed += _ => OnJoinRequested?.Invoke(id);

        var observe = new Button
        {
            Text = Loc.GetString("arena-lobby-observe"),
            Disabled = !IsObservablePhase(entry.Phase),
            MinSize = ButtonMinSize,
        };
        observe.OnPressed += _ => OnObserveRequested?.Invoke(id);

        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            VerticalAlignment = VAlignment.Center,
            SeparationOverride = 8,
            Margin = RowMargin,
            Children = { name, status, players, join, observe },
        };

        var body = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            SeparationOverride = 0,
            Children = { row },
        };

        if (!string.IsNullOrWhiteSpace(entry.Creator))
        {
            body.AddChild(new Label
            {
                Text = Loc.GetString("arena-lobby-creator", ("name", entry.Creator)),
                StyleClasses = { "LabelSubText" },
                FontColorOverride = ColorDescription,
                Margin = new Thickness(12, 0, 0, 4),
            });
        }

        return new PanelContainer
        {
            StyleClasses = { "AngleRect" },
            HorizontalExpand = true,
            Children = { body },
        };
    }

    private PanelContainer BuildTemplateRow(ArenaLobbyTemplate tmpl, bool canCreate)
    {
        var name = new Label
        {
            Text = tmpl.Name,
            StyleClasses = { "LabelKeyText" },
            HorizontalExpand = true,
        };

        var size = new Label
        {
            Text = Loc.GetString("arena-lobby-template-size", ("count", tmpl.MaxPlayers)),
            StyleClasses = { "LabelSubText" },
            Margin = PlayersMargin,
        };

        var create = new Button
        {
            Text = Loc.GetString("arena-lobby-create"),
            Disabled = !canCreate,
            MinSize = ButtonMinSize,
        };
        var protoId = tmpl.Id;
        create.OnPressed += _ => OnCreateRequested?.Invoke(protoId);

        var top = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            VerticalAlignment = VAlignment.Center,
            SeparationOverride = 8,
            Children = { name, size, create },
        };

        var body = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            Margin = RowMargin,
            SeparationOverride = 2,
            Children = { top },
        };

        if (!string.IsNullOrWhiteSpace(tmpl.Description))
        {
            body.AddChild(new Label
            {
                Text = tmpl.Description,
                StyleClasses = { "LabelSubText" },
                FontColorOverride = ColorDescription,
            });
        }

        return new PanelContainer
        {
            StyleClasses = { "AngleRect" },
            HorizontalExpand = true,
            Children = { body },
        };
    }
}
