- type: job
  id: RedWingsPilot
  name: ghost-role-information-redwings-pilot-name
  description: ghost-role-information-redwings-pilot-description
  playTimeTracker: JobRedWingsPilot
  experienceDefinition: SecurityPilotRoleExperience
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 50h
    - !type:RoleTimeRequirement
      role: JobSecurityPilot
      time: 10h
    - !type:RoleTimeRequirement
      role: JobBlueShield
      time: 10h
  canBeAntag: false
  icon: JobIconRedWingsPilot
  setPreference: false
  access:
  - Medical
  - Brig
  - Maintenance
  - External
  - Interdyne
