using Content.Shared.SS220.Shitspawn.SlotMachine;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Random;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.SS220.Shitspawn.SlotMachine.Ui;

[GenerateTypedNameReferences]
public sealed partial class SlotMachineWindow : DefaultWindow
{
    [Dependency] private readonly IRobustRandom _random = default!;
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    public event Action<int>? OnSpin;
    public event Action<int>? OnInsert;
    public event Action? OnCollect;

    private int _bet = SlotMachineComponent.MinBet;
    private bool _isSpinning;
    private TimeSpan _lastAnimFrame;

    private static readonly TimeSpan AnimInterval = TimeSpan.FromMilliseconds(120);
    private static readonly ResPath RsiPath = new("/Textures/SS220/Shitspawn/Structures/Machines/slot_machine.rsi");
    private static readonly string[] AnimSymbols = { "cherry", "apple", "blue_cherry", "bell", "seven", "diamond" };

    public SlotMachineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SpinButton.OnPressed         += _ => OnSpin?.Invoke(_bet);
        CollectButton.OnPressed      += _ => OnCollect?.Invoke();
        Insert10Button.OnPressed     += _ => OnInsert?.Invoke(10);
        Insert100Button.OnPressed    += _ => OnInsert?.Invoke(100);
        Insert1000Button.OnPressed   += _ => OnInsert?.Invoke(1000);
        Insert5000Button.OnPressed   += _ => OnInsert?.Invoke(5000);
        BetMinus1000Button.OnPressed += _ => SetBet(_bet - 1000);
        BetMinus100Button.OnPressed  += _ => SetBet(_bet - 100);
        BetPlus100Button.OnPressed   += _ => SetBet(_bet + 100);
        BetPlus1000Button.OnPressed  += _ => SetBet(_bet + 1000);
        BetPlus5000Button.OnPressed  += _ => SetBet(_bet + 5000);

        Insert10Button.Text   = Loc.GetString("slot-machine-ui-insert", ("amount", 10));
        Insert100Button.Text  = Loc.GetString("slot-machine-ui-insert", ("amount", 100));
        Insert1000Button.Text = Loc.GetString("slot-machine-ui-insert", ("amount", 1000));
        Insert5000Button.Text = Loc.GetString("slot-machine-ui-insert", ("amount", 5000));

        InitializePayoutTable();
    }

    private void InitializePayoutTable()
    {
        SetTripleTexture(PayDiamond1, PayDiamond2, PayDiamond3, "diamond");
        SetTripleTexture(PaySeven1,   PaySeven2,   PaySeven3,   "seven");
        SetTripleTexture(PayBell1,    PayBell2,    PayBell3,    "bell");
        SetTripleTexture(PayCherry1,  PayCherry2,  PayCherry3,  "cherry");
        SetTripleTexture(PayApple1,   PayApple2,   PayApple3,   "apple");
        SetTripleTexture(PayBlue1,    PayBlue2,    PayBlue3,    "blue_cherry");

        SetReelTexture(PayApplePairL1, "apple");
        SetReelTexture(PayApplePairL2, "apple");
        SetReelTexture(PayCherryPairR1, "cherry");
        SetReelTexture(PayCherryPairR2, "cherry");
    }

    private void SetTripleTexture(TextureRect r1, TextureRect r2, TextureRect r3, string symbol)
    {
        SetReelTexture(r1, symbol);
        SetReelTexture(r2, symbol);
        SetReelTexture(r3, symbol);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_isSpinning) return;

        var now = _gameTiming.RealTime;
        if (now - _lastAnimFrame < AnimInterval) return;
        _lastAnimFrame = now;

        SetReelTexture(Reel0Rect, AnimSymbols[_random.Next(AnimSymbols.Length)]);
        SetReelTexture(Reel1Rect, AnimSymbols[_random.Next(AnimSymbols.Length)]);
        SetReelTexture(Reel2Rect, AnimSymbols[_random.Next(AnimSymbols.Length)]);
    }

    private void SetBet(int value)
    {
        _bet = Math.Max(SlotMachineComponent.MinBet, value);
        BetLabel.Text = _bet.ToString();
    }

    public void UpdateState(SlotMachineBoundUserInterfaceState state)
    {
        _isSpinning = state.IsSpinning;

        if (!state.IsSpinning)
        {
            SetReelTexture(Reel0Rect, state.Reels[0]);
            SetReelTexture(Reel1Rect, state.Reels[1]);
            SetReelTexture(Reel2Rect, state.Reels[2]);
        }

        CreditsLabel.Text = Loc.GetString("slot-machine-ui-deposit", ("amount", state.StoredCredits));

        var winSymbol = state.Reels[0] switch
        {
            "cherry"      => Loc.GetString("slot-machine-symbol-cherry"),
            "apple"       => Loc.GetString("slot-machine-symbol-apple"),
            "blue_cherry" => Loc.GetString("slot-machine-symbol-blue-cherry"),
            "bell"        => Loc.GetString("slot-machine-symbol-bell"),
            _             => ""
        };

        PayoutLabel.Text = state.IsSpinning ? Loc.GetString("slot-machine-ui-spinning") : state.LastResult switch
        {
            SlotMachineResult.Jackpot    => Loc.GetString("slot-machine-ui-win-jackpot", ("amount", state.LastPayout)),
            SlotMachineResult.Triple7    => Loc.GetString("slot-machine-ui-win-777", ("amount", state.LastPayout)),
            SlotMachineResult.Triple     => Loc.GetString("slot-machine-ui-win-triple", ("symbol", winSymbol), ("amount", state.LastPayout)),
            SlotMachineResult.ApplePair  => Loc.GetString("slot-machine-ui-win-apples", ("amount", state.LastPayout)),
            SlotMachineResult.CherryPair => Loc.GetString("slot-machine-ui-win-cherries", ("amount", state.LastPayout)),
            SlotMachineResult.Lose       => Loc.GetString("slot-machine-ui-lose"),
            _                            => Loc.GetString("slot-machine-ui-luck"),
        };

        _bet = Math.Max(SlotMachineComponent.MinBet, Math.Min(_bet, state.StoredCredits > 0 ? state.StoredCredits : SlotMachineComponent.MinBet));
        BetLabel.Text = _bet.ToString();

        SpinButton.Disabled          = state.IsSpinning || state.StoredCredits < SlotMachineComponent.MinBet;
        CollectButton.Disabled       = state.IsSpinning || state.StoredCredits < 1;
        BetMinus1000Button.Disabled  = state.IsSpinning;
        BetMinus100Button.Disabled   = state.IsSpinning;
        BetPlus100Button.Disabled    = state.IsSpinning;
        BetPlus1000Button.Disabled   = state.IsSpinning;
        BetPlus5000Button.Disabled   = state.IsSpinning;
        Insert10Button.Disabled      = state.IsSpinning;
        Insert100Button.Disabled     = state.IsSpinning;
        Insert1000Button.Disabled    = state.IsSpinning;
        Insert5000Button.Disabled    = state.IsSpinning;
    }

    private void SetReelTexture(TextureRect rect, string symbol)
    {
        var rsi = _resourceCache.GetResource<RSIResource>(RsiPath);
        if (rsi.RSI.TryGetState(symbol, out var rsiState))
            rect.Texture = rsiState.Frame0;
    }
}
