using System.Numerics;
using Content.Shared.SS220.Shitspawn.SlotMachine;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Random;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.SS220.Shitspawn.SlotMachine.Ui;

[GenerateTypedNameReferences]
public sealed partial class SlotMachineWindow : DefaultWindow
{
    [Dependency] private readonly IRobustRandom _random = default!;
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    public event Action<int>? OnSpin;
    public event Action<int>? OnInsert;
    public event Action? OnCollect;

    private int _bet = SlotMachineComponent.MinBet;
    private bool _isSpinning;
    private TimeSpan _lastAnimFrame;
    private bool _payoutTableInitialized;
    private List<List<string>> _currentReelPools = new();

    private static readonly TimeSpan AnimInterval = TimeSpan.FromMilliseconds(120);
    private static readonly ResPath RsiPath = new("/Textures/SS220/Shitspawn/Structures/Machines/slot_machine.rsi");

    private static readonly Vector2 ReelTexRectSize = new(24, 24);
    private static readonly Color PayoutQuestionMarkColor = Color.FromHex("#555555");
    private const int PayoutSymbolsSeparation = 2;

    private const int InsertAmountSmall = 10;
    private const int InsertAmountMedium = 100;
    private const int InsertAmountLarge = 1000;
    private const int InsertAmountHuge = 5000;

    private const int BetAdjustSmall = 100;
    private const int BetAdjustLarge = 1000;
    private const int BetAdjustHuge = 5000;

    private const int MinimumCollectAmount = 1;

    public SlotMachineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SpinButton.OnPressed += _ => OnSpin?.Invoke(_bet);
        CollectButton.OnPressed += _ => OnCollect?.Invoke();
        Insert10Button.OnPressed += _ => OnInsert?.Invoke(InsertAmountSmall);
        Insert100Button.OnPressed += _ => OnInsert?.Invoke(InsertAmountMedium);
        Insert1000Button.OnPressed += _ => OnInsert?.Invoke(InsertAmountLarge);
        Insert5000Button.OnPressed += _ => OnInsert?.Invoke(InsertAmountHuge);
        BetMinus1000Button.OnPressed += _ => SetBet(_bet - BetAdjustLarge);
        BetMinus100Button.OnPressed += _ => SetBet(_bet - BetAdjustSmall);
        BetPlus100Button.OnPressed += _ => SetBet(_bet + BetAdjustSmall);
        BetPlus1000Button.OnPressed += _ => SetBet(_bet + BetAdjustLarge);
        BetPlus5000Button.OnPressed += _ => SetBet(_bet + BetAdjustHuge);

        Insert10Button.Text = Loc.GetString("slot-machine-ui-insert", ("amount", InsertAmountSmall));
        Insert100Button.Text = Loc.GetString("slot-machine-ui-insert", ("amount", InsertAmountMedium));
        Insert1000Button.Text = Loc.GetString("slot-machine-ui-insert", ("amount", InsertAmountLarge));
        Insert5000Button.Text = Loc.GetString("slot-machine-ui-insert", ("amount", InsertAmountHuge));
    }

    private void InitializePayoutTable(List<SlotMachineRule> rules, List<List<string>> pools)
    {
        if (_payoutTableInitialized) return;
        _payoutTableInitialized = true;

        PayoutTableContainer.DisposeAllChildren();

        foreach (var rule in rules)
        {
            if (rule.Symbols == null)
                continue;

            var symbolsContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = PayoutSymbolsSeparation
            };

            var maxReels = pools.Count;
            var startIdx = rule.Index ?? 0;

            for (var i = 0; i < maxReels; i++)
            {
                if (i >= startIdx && i < startIdx + rule.Symbols.Count)
                {
                    var rect = new TextureRect
                    {
                        MinSize = ReelTexRectSize,
                        HorizontalAlignment = HAlignment.Center,
                        VerticalAlignment = VAlignment.Center,
                        Stretch = TextureRect.StretchMode.KeepAspectCentered,
                    };
                    SetReelTexture(rect, rule.Symbols[i - startIdx]);
                    symbolsContainer.AddChild(rect);
                }
                else
                {
                    symbolsContainer.AddChild(new Label
                    {
                        Text = "?",
                        MinSize = ReelTexRectSize,
                        HorizontalAlignment = HAlignment.Center,
                        VerticalAlignment = VAlignment.Center,
                        FontColorOverride = PayoutQuestionMarkColor,
                        Align = Label.AlignMode.Center,
                    });
                }
            }

            PayoutTableContainer.AddChild(symbolsContainer);

            var multiplierLabel = new Label
            {
                Text = $"x{rule.Multiplier}",
                VerticalAlignment = VAlignment.Center,
                FontColorOverride = rule.Result switch
                {
                    SlotMachineResult.Jackpot => Color.Gold,
                    SlotMachineResult.Triple7 => Color.Red,
                    _ => Color.White
                },
            };
            PayoutTableContainer.AddChild(multiplierLabel);
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_isSpinning)
            return;

        var now = _gameTiming.RealTime;
        if (now - _lastAnimFrame < AnimInterval)
            return;
        _lastAnimFrame = now;

        SetReelTexture(Reel0Rect, GetRandomSymbol());
        SetReelTexture(Reel1Rect, GetRandomSymbol());
        SetReelTexture(Reel2Rect, GetRandomSymbol());
    }

    private void SetBet(int value)
    {
        _bet = Math.Max(SlotMachineComponent.MinBet, value);
        BetLabel.Text = _bet.ToString();
    }

    public void UpdateState(SlotMachineBoundUserInterfaceState state)
    {
        _isSpinning = state.IsSpinning;
        _currentReelPools = state.ReelPools;

        InitializePayoutTable(state.Rules, state.ReelPools);

        if (!state.IsSpinning)
        {
            if (state.Reels.Count >= 1)
                SetReelTexture(Reel0Rect, state.Reels[0]);
            if (state.Reels.Count >= 2)
                SetReelTexture(Reel1Rect, state.Reels[1]);
            if (state.Reels.Count >= 3)
                SetReelTexture(Reel2Rect, state.Reels[2]);
        }

        CreditsLabel.Text = Loc.GetString("slot-machine-ui-deposit", ("amount", state.StoredCredits));

        var winSymbol = state.Reels.Count > 0
            ? state.Reels[0] switch
        {
            "cherry"      => Loc.GetString("slot-machine-symbol-cherry"),
            "apple"       => Loc.GetString("slot-machine-symbol-apple"),
            "blue_cherry" => Loc.GetString("slot-machine-symbol-blue-cherry"),
            "bell"        => Loc.GetString("slot-machine-symbol-bell"),
            _             => ""
        }
            : "";

        PayoutLabel.Text = state.IsSpinning
            ? Loc.GetString("slot-machine-ui-spinning")
            : state.IsWin
                ? Loc.GetString(state.WinText, ("amount", state.LastPayout))
                : Loc.GetString("slot-machine-ui-lose");

        _bet = Math.Max(SlotMachineComponent.MinBet, Math.Min(_bet, state.StoredCredits > 0 ? state.StoredCredits : SlotMachineComponent.MinBet));
        BetLabel.Text = _bet.ToString();

        SpinButton.Disabled = state.IsSpinning || state.StoredCredits < SlotMachineComponent.MinBet;
        CollectButton.Disabled = state.IsSpinning || state.StoredCredits < MinimumCollectAmount;
        BetMinus1000Button.Disabled = state.IsSpinning;
        BetMinus100Button.Disabled = state.IsSpinning;
        BetPlus100Button.Disabled = state.IsSpinning;
        BetPlus1000Button.Disabled = state.IsSpinning;
        BetPlus5000Button.Disabled = state.IsSpinning;
        Insert10Button.Disabled = state.IsSpinning;
        Insert100Button.Disabled = state.IsSpinning;
        Insert1000Button.Disabled = state.IsSpinning;
        Insert5000Button.Disabled = state.IsSpinning;
    }

    private void SetReelTexture(TextureRect rect, string symbol)
    {
        var rsi = _resourceCache.GetResource<RSIResource>(RsiPath);
        if (rsi.RSI.TryGetState(symbol, out var rsiState))
            rect.Texture = rsiState.Frame0;
    }

    private string GetRandomSymbol()
    {
        if (_currentReelPools.Count == 0 || _currentReelPools[0].Count == 0)
            return "seven"; // fallback

        return _random.Pick(_currentReelPools[0]);
    }
}
