using Content.Shared.SS220.Administration.Events;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class CustomObjectivesWindow : DefaultWindow
{
    [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    private CustomObjectivesPlayerInfo? _selectedPlayerInfo;

    public CustomObjectivesWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        CustomObjectivesList.OnSelectionChanged += OnSelectionChanged;
        ListOfObjectivesButton.OnPressed += OnListOfObjectivesPressed;
        AddObjectiveButton.OnWindowCreated += OnAddObjectiveWindowCreated;
        _consoleHost.ExecuteCommand("requestcustomobjectives");
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        CustomObjectivesList.OnSelectionChanged -= OnSelectionChanged;
        ListOfObjectivesButton.OnPressed -= OnListOfObjectivesPressed;
        AddObjectiveButton.OnWindowCreated -= OnAddObjectiveWindowCreated;
    }

    private void OnSelectionChanged(CustomObjectivesPlayerInfo? playerInfo)
    {
        _selectedPlayerInfo = playerInfo;
        var disabled = playerInfo is null;
        ListOfObjectivesButton.Disabled = disabled;
        AddObjectiveButton.Disabled = disabled;
    }

    private void OnListOfObjectivesPressed(BaseButton.ButtonEventArgs args)
    {
        if (_selectedPlayerInfo is not { } playerInfo)
            return;

        _consoleHost.ExecuteCommand($"openobjectives {playerInfo.SessionId}");
    }

    private void OnAddObjectiveWindowCreated(DefaultWindow window)
    {
        if (_selectedPlayerInfo is not { } playerInfo ||
            !_playerManager.TryGetSessionById(playerInfo.SessionId, out var session))
        {
            return;
        }

        if (window is AddObjectiveWindow addObjectiveWindow)
            addObjectiveWindow.SetAntagonist(session);
    }
}
