using Content.Shared.Administration;
using Content.Shared.SS220.Administration.Events;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;

namespace Content.Client.SS220.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    [UsedImplicitly]
    public sealed partial class CustomObjectivesWindow : DefaultWindow
    {
        private CustomObjectivesPlayerInfo? _selectedPlayer;

        protected override void EnteredTree()
        {
            base.EnteredTree();
            CustomObjectivesList.OnSelectionChanged += OnSelectionChanged;
            ListOfObjectivesButton.OnPressed += ListOfObjectivesButtonOnPressed;
            AddObjectiveButton.OnWindowCreated += AddObjectiveButtonOnWindowCreated;
            IoCManager.Resolve<IClientConsoleHost>().ExecuteCommand("requestcustomobjectives");
        }

        private void OnSelectionChanged(CustomObjectivesPlayerInfo? obj)
        {
            _selectedPlayer = obj;
            var disableButtons = _selectedPlayer == null;
            ListOfObjectivesButton.Disabled = disableButtons;
            AddObjectiveButton.Disabled = disableButtons;
        }

        private void ListOfObjectivesButtonOnPressed(BaseButton.ButtonEventArgs obj)
        {
            if (_selectedPlayer == null)
                return;

            IoCManager.Resolve<IClientConsoleHost>().ExecuteCommand(
                $"openobjectives {_selectedPlayer.SessionId}");
        }

        private void AddObjectiveButtonOnWindowCreated(DefaultWindow window)
        {
            if (_selectedPlayer is null)
                return;

            var addObjectiveWindow = (AddObjectiveWindow) window;
            var playerSession = IoCManager.Resolve<IPlayerManager>().GetSessionById(_selectedPlayer.SessionId);
            addObjectiveWindow.SetAntagonist(playerSession);
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();
            CustomObjectivesList.OnSelectionChanged -= OnSelectionChanged;
            ListOfObjectivesButton.OnPressed -= ListOfObjectivesButtonOnPressed;
            AddObjectiveButton.OnWindowCreated -= AddObjectiveButtonOnWindowCreated;
        }
    }
}
